package db

// spanishSeedData contains ~400 common Spanish vocabulary words for new users.
// The Finnish field holds the Spanish word (base/dictionary form).
// Organized by category for maintainability.
var spanishSeedData = []seedEntry{
	// ── Pronouns (12) ──
	{"yo", "yo", "pronoun", "I"},
	{"tú", "tú", "pronoun", "you (informal)"},
	{"él", "él", "pronoun", "he"},
	{"ella", "ella", "pronoun", "she"},
	{"nosotros", "nosotros", "pronoun", "we"},
	{"vosotros", "vosotros", "pronoun", "you all (Spain)"},
	{"ellos", "ellos", "pronoun", "they (masc.)"},
	{"ellas", "ellas", "pronoun", "they (fem.)"},
	{"usted", "usted", "pronoun", "you (formal)"},
	{"ustedes", "ustedes", "pronoun", "you all (formal)"},
	{"este", "este", "pronoun", "this"},
	{"ese", "ese", "pronoun", "that"},

	// ── Verbs: Core (30) ──
	{"ser", "ser", "verb", "to be (permanent)"},
	{"estar", "estar", "verb", "to be (temporary/state)"},
	{"tener", "tener", "verb", "to have"},
	{"hacer", "hacer", "verb", "to do/make"},
	{"ir", "ir", "verb", "to go"},
	{"venir", "venir", "verb", "to come"},
	{"poder", "poder", "verb", "to be able to/can"},
	{"querer", "querer", "verb", "to want/love"},
	{"saber", "saber", "verb", "to know (a fact)"},
	{"conocer", "conocer", "verb", "to know (a person/place)"},
	{"decir", "decir", "verb", "to say/tell"},
	{"ver", "ver", "verb", "to see"},
	{"dar", "dar", "verb", "to give"},
	{"tomar", "tomar", "verb", "to take/drink"},
	{"llevar", "llevar", "verb", "to carry/wear/take"},
	{"traer", "traer", "verb", "to bring"},
	{"poner", "poner", "verb", "to put/place"},
	{"salir", "salir", "verb", "to leave/go out"},
	{"llegar", "llegar", "verb", "to arrive"},
	{"pasar", "pasar", "verb", "to pass/happen/spend (time)"},
	{"deber", "deber", "verb", "to owe/must/should"},
	{"necesitar", "necesitar", "verb", "to need"},
	{"dejar", "dejar", "verb", "to leave/let/allow"},
	{"seguir", "seguir", "verb", "to follow/continue"},
	{"encontrar", "encontrar", "verb", "to find/meet"},
	{"pensar", "pensar", "verb", "to think"},
	{"creer", "creer", "verb", "to believe/think"},
	{"sentir", "sentir", "verb", "to feel"},
	{"llamar", "llamar", "verb", "to call"},
	{"parecer", "parecer", "verb", "to seem/appear"},

	// ── Verbs: Daily Life (30) ──
	{"hablar", "hablar", "verb", "to speak/talk"},
	{"escuchar", "escuchar", "verb", "to listen"},
	{"leer", "leer", "verb", "to read"},
	{"escribir", "escribir", "verb", "to write"},
	{"comer", "comer", "verb", "to eat"},
	{"beber", "beber", "verb", "to drink"},
	{"dormir", "dormir", "verb", "to sleep"},
	{"despertar", "despertar", "verb", "to wake up"},
	{"levantarse", "levantarse", "verb", "to get up"},
	{"sentarse", "sentarse", "verb", "to sit down"},
	{"caminar", "caminar", "verb", "to walk"},
	{"correr", "correr", "verb", "to run"},
	{"trabajar", "trabajar", "verb", "to work"},
	{"estudiar", "estudiar", "verb", "to study"},
	{"aprender", "aprender", "verb", "to learn"},
	{"enseñar", "enseñar", "verb", "to teach"},
	{"comprar", "comprar", "verb", "to buy"},
	{"vender", "vender", "verb", "to sell"},
	{"pagar", "pagar", "verb", "to pay"},
	{"abrir", "abrir", "verb", "to open"},
	{"cerrar", "cerrar", "verb", "to close"},
	{"cocinar", "cocinar", "verb", "to cook"},
	{"limpiar", "limpiar", "verb", "to clean"},
	{"ayudar", "ayudar", "verb", "to help"},
	{"esperar", "esperar", "verb", "to wait/hope"},
	{"buscar", "buscar", "verb", "to look for/search"},
	{"preguntar", "preguntar", "verb", "to ask"},
	{"contestar", "contestar", "verb", "to answer"},
	{"entender", "entender", "verb", "to understand"},
	{"vivir", "vivir", "verb", "to live"},

	// ── Verbs: Social & Other (15) ──
	{"gustar", "gustar", "verb", "to like (be pleasing)"},
	{"amar", "amar", "verb", "to love"},
	{"odiar", "odiar", "verb", "to hate"},
	{"recordar", "recordar", "verb", "to remember"},
	{"olvidar", "olvidar", "verb", "to forget"},
	{"empezar", "empezar", "verb", "to begin/start"},
	{"terminar", "terminar", "verb", "to finish/end"},
	{"volver", "volver", "verb", "to return"},
	{"entrar", "entrar", "verb", "to enter"},
	{"mirar", "mirar", "verb", "to look at/watch"},
	{"jugar", "jugar", "verb", "to play (games/sports)"},
	{"cantar", "cantar", "verb", "to sing"},
	{"bailar", "bailar", "verb", "to dance"},
	{"viajar", "viajar", "verb", "to travel"},
	{"nacer", "nacer", "verb", "to be born"},

	// ── Nouns: People & Relationships (25) ──
	{"persona", "persona", "noun", "person"},
	{"hombre", "hombre", "noun", "man"},
	{"mujer", "mujer", "noun", "woman"},
	{"niño", "niño", "noun", "boy/child"},
	{"niña", "niña", "noun", "girl"},
	{"bebé", "bebé", "noun", "baby"},
	{"familia", "familia", "noun", "family"},
	{"madre", "madre", "noun", "mother"},
	{"padre", "padre", "noun", "father"},
	{"hermano", "hermano", "noun", "brother"},
	{"hermana", "hermana", "noun", "sister"},
	{"abuelo", "abuelo", "noun", "grandfather"},
	{"abuela", "abuela", "noun", "grandmother"},
	{"esposo", "esposo", "noun", "husband"},
	{"esposa", "esposa", "noun", "wife"},
	{"hijo", "hijo", "noun", "son"},
	{"hija", "hija", "noun", "daughter"},
	{"amigo", "amigo", "noun", "friend (masc.)"},
	{"amiga", "amiga", "noun", "friend (fem.)"},
	{"vecino", "vecino", "noun", "neighbor"},
	{"profesor", "profesor", "noun", "teacher (masc.)"},
	{"estudiante", "estudiante", "noun", "student"},
	{"médico", "médico", "noun", "doctor"},
	{"jefe", "jefe", "noun", "boss/chief"},
	{"compañero", "compañero", "noun", "colleague/companion"},

	// ── Nouns: Home & Household (20) ──
	{"casa", "casa", "noun", "house/home"},
	{"apartamento", "apartamento", "noun", "apartment"},
	{"habitación", "habitación", "noun", "room/bedroom"},
	{"cocina", "cocina", "noun", "kitchen"},
	{"sala", "sala", "noun", "living room"},
	{"baño", "baño", "noun", "bathroom"},
	{"puerta", "puerta", "noun", "door"},
	{"ventana", "ventana", "noun", "window"},
	{"suelo", "suelo", "noun", "floor/ground"},
	{"pared", "pared", "noun", "wall"},
	{"silla", "silla", "noun", "chair"},
	{"mesa", "mesa", "noun", "table"},
	{"cama", "cama", "noun", "bed"},
	{"sofá", "sofá", "noun", "sofa"},
	{"llave", "llave", "noun", "key"},
	{"lámpara", "lámpara", "noun", "lamp"},
	{"espejo", "espejo", "noun", "mirror"},
	{"teléfono", "teléfono", "noun", "telephone"},
	{"libro", "libro", "noun", "book"},
	{"bolsa", "bolsa", "noun", "bag/purse"},

	// ── Nouns: Food & Drink (30) ──
	{"comida", "comida", "noun", "food/meal"},
	{"agua", "agua", "noun", "water"},
	{"pan", "pan", "noun", "bread"},
	{"leche", "leche", "noun", "milk"},
	{"café", "café", "noun", "coffee"},
	{"té", "té", "noun", "tea"},
	{"jugo", "jugo", "noun", "juice"},
	{"vino", "vino", "noun", "wine"},
	{"cerveza", "cerveza", "noun", "beer"},
	{"carne", "carne", "noun", "meat"},
	{"pescado", "pescado", "noun", "fish"},
	{"pollo", "pollo", "noun", "chicken"},
	{"queso", "queso", "noun", "cheese"},
	{"mantequilla", "mantequilla", "noun", "butter"},
	{"huevo", "huevo", "noun", "egg"},
	{"arroz", "arroz", "noun", "rice"},
	{"papa", "papa", "noun", "potato"},
	{"fruta", "fruta", "noun", "fruit"},
	{"manzana", "manzana", "noun", "apple"},
	{"naranja", "naranja", "noun", "orange"},
	{"tomate", "tomate", "noun", "tomato"},
	{"cebolla", "cebolla", "noun", "onion"},
	{"verdura", "verdura", "noun", "vegetable"},
	{"sal", "sal", "noun", "salt"},
	{"azúcar", "azúcar", "noun", "sugar"},
	{"aceite", "aceite", "noun", "oil"},
	{"sopa", "sopa", "noun", "soup"},
	{"desayuno", "desayuno", "noun", "breakfast"},
	{"almuerzo", "almuerzo", "noun", "lunch"},
	{"cena", "cena", "noun", "dinner"},

	// ── Nouns: Body & Health (20) ──
	{"cabeza", "cabeza", "noun", "head"},
	{"cara", "cara", "noun", "face"},
	{"ojo", "ojo", "noun", "eye"},
	{"oído", "oído", "noun", "ear"},
	{"nariz", "nariz", "noun", "nose"},
	{"boca", "boca", "noun", "mouth"},
	{"diente", "diente", "noun", "tooth"},
	{"mano", "mano", "noun", "hand"},
	{"dedo", "dedo", "noun", "finger"},
	{"pie", "pie", "noun", "foot"},
	{"pierna", "pierna", "noun", "leg"},
	{"espalda", "espalda", "noun", "back"},
	{"corazón", "corazón", "noun", "heart"},
	{"salud", "salud", "noun", "health"},
	{"enfermedad", "enfermedad", "noun", "illness/disease"},
	{"dolor", "dolor", "noun", "pain"},
	{"medicina", "medicina", "noun", "medicine"},
	{"hospital", "hospital", "noun", "hospital"},
	{"farmacia", "farmacia", "noun", "pharmacy"},
	{"fiebre", "fiebre", "noun", "fever"},

	// ── Nouns: Places & Buildings (20) ──
	{"lugar", "lugar", "noun", "place"},
	{"ciudad", "ciudad", "noun", "city"},
	{"pueblo", "pueblo", "noun", "town/village"},
	{"país", "país", "noun", "country"},
	{"calle", "calle", "noun", "street"},
	{"escuela", "escuela", "noun", "school"},
	{"universidad", "universidad", "noun", "university"},
	{"biblioteca", "biblioteca", "noun", "library"},
	{"tienda", "tienda", "noun", "store/shop"},
	{"mercado", "mercado", "noun", "market"},
	{"restaurante", "restaurante", "noun", "restaurant"},
	{"banco", "banco", "noun", "bank"},
	{"iglesia", "iglesia", "noun", "church"},
	{"museo", "museo", "noun", "museum"},
	{"hotel", "hotel", "noun", "hotel"},
	{"aeropuerto", "aeropuerto", "noun", "airport"},
	{"estación", "estación", "noun", "station"},
	{"oficina", "oficina", "noun", "office"},
	{"parque", "parque", "noun", "park"},
	{"playa", "playa", "noun", "beach"},

	// ── Nouns: Nature & Weather (20) ──
	{"naturaleza", "naturaleza", "noun", "nature"},
	{"bosque", "bosque", "noun", "forest"},
	{"lago", "lago", "noun", "lake"},
	{"río", "río", "noun", "river"},
	{"mar", "mar", "noun", "sea"},
	{"montaña", "montaña", "noun", "mountain"},
	{"árbol", "árbol", "noun", "tree"},
	{"flor", "flor", "noun", "flower"},
	{"tiempo", "tiempo", "noun", "weather/time"},
	{"sol", "sol", "noun", "sun"},
	{"luna", "luna", "noun", "moon"},
	{"estrella", "estrella", "noun", "star"},
	{"cielo", "cielo", "noun", "sky/heaven"},
	{"nube", "nube", "noun", "cloud"},
	{"lluvia", "lluvia", "noun", "rain"},
	{"nieve", "nieve", "noun", "snow"},
	{"viento", "viento", "noun", "wind"},
	{"primavera", "primavera", "noun", "spring"},
	{"verano", "verano", "noun", "summer"},
	{"invierno", "invierno", "noun", "winter"},

	// ── Nouns: Time & Calendar (15) ──
	{"tiempo", "tiempo", "noun", "time/weather"},
	{"día", "día", "noun", "day"},
	{"noche", "noche", "noun", "night"},
	{"mañana", "mañana", "noun", "morning/tomorrow"},
	{"tarde", "tarde", "noun", "afternoon/evening"},
	{"hora", "hora", "noun", "hour"},
	{"minuto", "minuto", "noun", "minute"},
	{"año", "año", "noun", "year"},
	{"mes", "mes", "noun", "month"},
	{"semana", "semana", "noun", "week"},
	{"fin de semana", "fin de semana", "noun", "weekend"},
	{"hoy", "hoy", "adverb", "today"},
	{"ayer", "ayer", "adverb", "yesterday"},
	{"vacaciones", "vacaciones", "noun", "vacation/holidays"},
	{"fiesta", "fiesta", "noun", "party/holiday/festival"},

	// ── Nouns: Transport & Travel (12) ──
	{"coche", "coche", "noun", "car"},
	{"autobús", "autobús", "noun", "bus"},
	{"tren", "tren", "noun", "train"},
	{"avión", "avión", "noun", "airplane"},
	{"barco", "barco", "noun", "ship/boat"},
	{"bicicleta", "bicicleta", "noun", "bicycle"},
	{"carretera", "carretera", "noun", "road/highway"},
	{"billete", "billete", "noun", "ticket/bill"},
	{"viaje", "viaje", "noun", "trip/journey"},
	{"mapa", "mapa", "noun", "map"},
	{"maleta", "maleta", "noun", "suitcase"},
	{"pasaporte", "pasaporte", "noun", "passport"},

	// ── Nouns: Clothing (10) ──
	{"ropa", "ropa", "noun", "clothing"},
	{"camisa", "camisa", "noun", "shirt"},
	{"pantalón", "pantalón", "noun", "pants/trousers"},
	{"zapato", "zapato", "noun", "shoe"},
	{"vestido", "vestido", "noun", "dress"},
	{"chaqueta", "chaqueta", "noun", "jacket"},
	{"abrigo", "abrigo", "noun", "coat"},
	{"calcetín", "calcetín", "noun", "sock"},
	{"sombrero", "sombrero", "noun", "hat"},
	{"bolso", "bolso", "noun", "handbag"},

	// ── Nouns: Animals (12) ──
	{"animal", "animal", "noun", "animal"},
	{"perro", "perro", "noun", "dog"},
	{"gato", "gato", "noun", "cat"},
	{"caballo", "caballo", "noun", "horse"},
	{"vaca", "vaca", "noun", "cow"},
	{"cerdo", "cerdo", "noun", "pig"},
	{"pájaro", "pájaro", "noun", "bird"},
	{"pez", "pez", "noun", "fish"},
	{"toro", "toro", "noun", "bull"},
	{"lobo", "lobo", "noun", "wolf"},
	{"ratón", "ratón", "noun", "mouse"},
	{"oso", "oso", "noun", "bear"},

	// ── Adjectives (40) ──
	{"bueno", "bueno", "adjective", "good"},
	{"malo", "malo", "adjective", "bad"},
	{"grande", "grande", "adjective", "big/great"},
	{"pequeño", "pequeño", "adjective", "small/little"},
	{"nuevo", "nuevo", "adjective", "new"},
	{"viejo", "viejo", "adjective", "old"},
	{"joven", "joven", "adjective", "young"},
	{"largo", "largo", "adjective", "long"},
	{"corto", "corto", "adjective", "short"},
	{"bonito", "bonito", "adjective", "pretty/nice"},
	{"feo", "feo", "adjective", "ugly"},
	{"fácil", "fácil", "adjective", "easy"},
	{"difícil", "difícil", "adjective", "difficult"},
	{"importante", "importante", "adjective", "important"},
	{"rápido", "rápido", "adjective", "fast/quick"},
	{"lento", "lento", "adjective", "slow"},
	{"caro", "caro", "adjective", "expensive"},
	{"barato", "barato", "adjective", "cheap"},
	{"caliente", "caliente", "adjective", "hot/warm"},
	{"frío", "frío", "adjective", "cold"},
	{"fuerte", "fuerte", "adjective", "strong"},
	{"débil", "débil", "adjective", "weak"},
	{"rico", "rico", "adjective", "rich/delicious"},
	{"pobre", "pobre", "adjective", "poor"},
	{"enfermo", "enfermo", "adjective", "sick/ill"},
	{"sano", "sano", "adjective", "healthy"},
	{"cansado", "cansado", "adjective", "tired"},
	{"contento", "contento", "adjective", "happy/pleased"},
	{"triste", "triste", "adjective", "sad"},
	{"enojado", "enojado", "adjective", "angry"},
	{"feliz", "feliz", "adjective", "happy/fortunate"},
	{"tranquilo", "tranquilo", "adjective", "calm/quiet"},
	{"limpio", "limpio", "adjective", "clean"},
	{"sucio", "sucio", "adjective", "dirty"},
	{"lleno", "lleno", "adjective", "full"},
	{"vacío", "vacío", "adjective", "empty"},
	{"abierto", "abierto", "adjective", "open"},
	{"cerrado", "cerrado", "adjective", "closed"},
	{"listo", "listo", "adjective", "ready/clever"},
	{"mismo", "mismo", "adjective", "same/itself"},

	// ── Colors (10) ──
	{"rojo", "rojo", "adjective", "red"},
	{"azul", "azul", "adjective", "blue"},
	{"verde", "verde", "adjective", "green"},
	{"amarillo", "amarillo", "adjective", "yellow"},
	{"blanco", "blanco", "adjective", "white"},
	{"negro", "negro", "adjective", "black"},
	{"gris", "gris", "adjective", "gray"},
	{"marrón", "marrón", "adjective", "brown"},
	{"naranja", "naranja", "adjective", "orange"},
	{"rosa", "rosa", "adjective", "pink"},

	// ── Numbers (15) ──
	{"uno", "uno", "numeral", "one"},
	{"dos", "dos", "numeral", "two"},
	{"tres", "tres", "numeral", "three"},
	{"cuatro", "cuatro", "numeral", "four"},
	{"cinco", "cinco", "numeral", "five"},
	{"seis", "seis", "numeral", "six"},
	{"siete", "siete", "numeral", "seven"},
	{"ocho", "ocho", "numeral", "eight"},
	{"nueve", "nueve", "numeral", "nine"},
	{"diez", "diez", "numeral", "ten"},
	{"cien", "cien", "numeral", "hundred"},
	{"mil", "mil", "numeral", "thousand"},
	{"primero", "primero", "numeral", "first"},
	{"segundo", "segundo", "numeral", "second"},
	{"último", "último", "numeral", "last"},

	// ── Adverbs (25) ──
	{"ahora", "ahora", "adverb", "now"},
	{"antes", "antes", "adverb", "before"},
	{"después", "después", "adverb", "after/later"},
	{"aquí", "aquí", "adverb", "here"},
	{"allí", "allí", "adverb", "there"},
	{"mucho", "mucho", "adverb", "much/a lot"},
	{"poco", "poco", "adverb", "a little/few"},
	{"muy", "muy", "adverb", "very"},
	{"bien", "bien", "adverb", "well"},
	{"mal", "mal", "adverb", "badly/poorly"},
	{"también", "también", "adverb", "also/too"},
	{"solo", "solo", "adverb", "only/alone"},
	{"ya", "ya", "adverb", "already/now"},
	{"todavía", "todavía", "adverb", "still/yet"},
	{"siempre", "siempre", "adverb", "always"},
	{"nunca", "nunca", "adverb", "never"},
	{"a veces", "a veces", "adverb", "sometimes"},
	{"quizás", "quizás", "adverb", "maybe/perhaps"},
	{"casi", "casi", "adverb", "almost"},
	{"bastante", "bastante", "adverb", "quite/enough"},
	{"pronto", "pronto", "adverb", "soon"},
	{"lejos", "lejos", "adverb", "far"},
	{"cerca", "cerca", "adverb", "near/close"},
	{"dentro", "dentro", "adverb", "inside"},
	{"fuera", "fuera", "adverb", "outside"},

	// ── Question Words (8) ──
	{"qué", "qué", "adverb", "what/which"},
	{"quién", "quién", "adverb", "who"},
	{"dónde", "dónde", "adverb", "where"},
	{"cuándo", "cuándo", "adverb", "when"},
	{"cómo", "cómo", "adverb", "how"},
	{"por qué", "por qué", "adverb", "why"},
	{"cuánto", "cuánto", "adverb", "how much/many"},
	{"cuál", "cuál", "adverb", "which"},

	// ── Conjunctions & Particles (15) ──
	{"y", "y", "conjunction", "and"},
	{"o", "o", "conjunction", "or"},
	{"pero", "pero", "conjunction", "but"},
	{"porque", "porque", "conjunction", "because"},
	{"que", "que", "conjunction", "that/which"},
	{"si", "si", "conjunction", "if"},
	{"cuando", "cuando", "conjunction", "when"},
	{"aunque", "aunque", "conjunction", "although/even if"},
	{"como", "como", "conjunction", "as/like/how"},
	{"mientras", "mientras", "conjunction", "while"},
	{"para", "para", "preposition", "for/in order to"},
	{"por", "por", "preposition", "for/by/through"},
	{"con", "con", "preposition", "with"},
	{"sin", "sin", "preposition", "without"},
	{"entre", "entre", "preposition", "between/among"},

	// ── Nouns: Abstract & Everyday (20) ──
	{"cosa", "cosa", "noun", "thing"},
	{"nombre", "nombre", "noun", "name"},
	{"idioma", "idioma", "noun", "language"},
	{"palabra", "palabra", "noun", "word"},
	{"pregunta", "pregunta", "noun", "question"},
	{"respuesta", "respuesta", "noun", "answer"},
	{"problema", "problema", "noun", "problem"},
	{"idea", "idea", "noun", "idea"},
	{"dinero", "dinero", "noun", "money"},
	{"precio", "precio", "noun", "price"},
	{"trabajo", "trabajo", "noun", "work/job"},
	{"vida", "vida", "noun", "life"},
	{"amor", "amor", "noun", "love"},
	{"miedo", "miedo", "noun", "fear"},
	{"verdad", "verdad", "noun", "truth"},
	{"noticia", "noticia", "noun", "news item"},
	{"mensaje", "mensaje", "noun", "message"},
	{"número", "número", "noun", "number"},
	{"parte", "parte", "noun", "part"},
	{"vez", "vez", "noun", "time/occasion"},

	// ── Nouns: Technology & Modern (8) ──
	{"computadora", "computadora", "noun", "computer"},
	{"internet", "internet", "noun", "internet"},
	{"correo electrónico", "correo electrónico", "noun", "email"},
	{"teléfono móvil", "teléfono móvil", "noun", "mobile phone"},
	{"foto", "foto", "noun", "photo"},
	{"música", "música", "noun", "music"},
	{"película", "película", "noun", "movie/film"},
	{"programa", "programa", "noun", "program/show"},

	// ── Greetings & Expressions (10) ──
	{"hola", "hola", "interjection", "hello/hi"},
	{"adiós", "adiós", "interjection", "goodbye"},
	{"hasta luego", "hasta luego", "interjection", "see you later"},
	{"gracias", "gracias", "interjection", "thank you"},
	{"de nada", "de nada", "interjection", "you're welcome"},
	{"por favor", "por favor", "interjection", "please"},
	{"perdón", "perdón", "interjection", "sorry/excuse me"},
	{"sí", "sí", "particle", "yes"},
	{"no", "no", "particle", "no"},
	{"claro", "claro", "particle", "of course/clear"},
}

// seedSpanishCards inserts Spanish seed vocabulary into the cards table (idempotent).
func (db *DB) seedSpanishCards() error {
	stmt, err := db.Prepare(`
		INSERT OR IGNORE INTO cards (finnish, lemma, word_class, translation, source)
		VALUES (?, ?, ?, ?, 'seed_es')
	`)
	if err != nil {
		return err
	}
	defer stmt.Close()

	for _, s := range spanishSeedData {
		if _, err := stmt.Exec(s.Finnish, s.Lemma, s.WordClass, s.Translation); err != nil {
			return err
		}
	}
	return nil
}
