package db

// seedEntry holds curated data for a pre-populated flashcard.
type seedEntry struct {
	Finnish     string
	Lemma       string
	WordClass   string
	Translation string
}

// seedData contains ~500 common Finnish vocabulary words for new users.
// All entries are base/dictionary forms. Organized by category for maintainability.
var seedData = []seedEntry{
	// ── Pronouns (17) ──
	{"minä", "minä", "pronoun", "I"},
	{"sinä", "sinä", "pronoun", "you (singular)"},
	{"hän", "hän", "pronoun", "he/she"},
	{"me", "me", "pronoun", "we"},
	{"te", "te", "pronoun", "you (plural/formal)"},
	{"he", "he", "pronoun", "they"},
	{"se", "se", "pronoun", "it"},
	{"ne", "ne", "pronoun", "they (things)"},
	{"tämä", "tämä", "pronoun", "this"},
	{"tuo", "tuo", "pronoun", "that"},
	{"nämä", "nämä", "pronoun", "these"},
	{"nuo", "nuo", "pronoun", "those"},
	{"mikä", "mikä", "pronoun", "what/which"},
	{"kuka", "kuka", "pronoun", "who"},
	{"joka", "joka", "pronoun", "who/which (relative)"},
	{"itse", "itse", "pronoun", "self"},
	{"toinen", "toinen", "pronoun", "other/another"},

	// ── Verbs (85) ──
	// Core / high-frequency
	{"olla", "olla", "verb", "to be"},
	{"ei", "ei", "verb", "not (negation word)"},
	{"tulla", "tulla", "verb", "to come"},
	{"mennä", "mennä", "verb", "to go"},
	{"tehdä", "tehdä", "verb", "to do/make"},
	{"sanoa", "sanoa", "verb", "to say"},
	{"saada", "saada", "verb", "to get/receive"},
	{"voida", "voida", "verb", "to be able/can"},
	{"pitää", "pitää", "verb", "to have to/like/hold"},
	{"antaa", "antaa", "verb", "to give"},
	{"ottaa", "ottaa", "verb", "to take"},
	{"nähdä", "nähdä", "verb", "to see"},
	{"tietää", "tietää", "verb", "to know (a fact)"},
	{"haluta", "haluta", "verb", "to want"},
	{"puhua", "puhua", "verb", "to speak/talk"},
	{"käyttää", "käyttää", "verb", "to use"},
	{"jäädä", "jäädä", "verb", "to stay/remain"},
	{"lähteä", "lähteä", "verb", "to leave/depart"},
	{"katsoa", "katsoa", "verb", "to look/watch"},
	{"kuulla", "kuulla", "verb", "to hear"},
	{"kysyä", "kysyä", "verb", "to ask"},
	{"vastata", "vastata", "verb", "to answer"},
	{"ymmärtää", "ymmärtää", "verb", "to understand"},
	{"tarvita", "tarvita", "verb", "to need"},
	{"täytyä", "täytyä", "verb", "must/have to"},
	// Daily life
	{"lukea", "lukea", "verb", "to read"},
	{"kirjoittaa", "kirjoittaa", "verb", "to write"},
	{"syödä", "syödä", "verb", "to eat"},
	{"juoda", "juoda", "verb", "to drink"},
	{"nukkua", "nukkua", "verb", "to sleep"},
	{"herätä", "herätä", "verb", "to wake up"},
	{"nousta", "nousta", "verb", "to rise/get up"},
	{"istua", "istua", "verb", "to sit"},
	{"seistä", "seistä", "verb", "to stand"},
	{"kävellä", "kävellä", "verb", "to walk"},
	{"juosta", "juosta", "verb", "to run"},
	{"ajaa", "ajaa", "verb", "to drive"},
	{"pestä", "pestä", "verb", "to wash"},
	{"pukea", "pukea", "verb", "to dress"},
	{"laittaa", "laittaa", "verb", "to put/prepare"},
	{"avata", "avata", "verb", "to open"},
	{"sulkea", "sulkea", "verb", "to close"},
	{"siivota", "siivota", "verb", "to clean"},
	{"kokata", "kokata", "verb", "to cook"},
	// Social / communication
	{"kertoa", "kertoa", "verb", "to tell"},
	{"pyytää", "pyytää", "verb", "to ask/request"},
	{"kiittää", "kiittää", "verb", "to thank"},
	{"tavata", "tavata", "verb", "to meet"},
	{"soittaa", "soittaa", "verb", "to call/play (instrument)"},
	{"lähettää", "lähettää", "verb", "to send"},
	// Learning / thinking
	{"oppia", "oppia", "verb", "to learn"},
	{"opettaa", "opettaa", "verb", "to teach"},
	{"opiskella", "opiskella", "verb", "to study"},
	{"ajatella", "ajatella", "verb", "to think"},
	{"muistaa", "muistaa", "verb", "to remember"},
	{"unohtaa", "unohtaa", "verb", "to forget"},
	{"uskoa", "uskoa", "verb", "to believe"},
	{"tuntea", "tuntea", "verb", "to feel/know (person)"},
	// Action / work
	{"asua", "asua", "verb", "to live/reside"},
	{"käydä", "käydä", "verb", "to visit/attend"},
	{"auttaa", "auttaa", "verb", "to help"},
	{"ostaa", "ostaa", "verb", "to buy"},
	{"myydä", "myydä", "verb", "to sell"},
	{"maksaa", "maksaa", "verb", "to pay/cost"},
	{"odottaa", "odottaa", "verb", "to wait/expect"},
	{"alkaa", "alkaa", "verb", "to begin"},
	{"loppua", "loppua", "verb", "to end"},
	{"löytää", "löytää", "verb", "to find"},
	{"etsiä", "etsiä", "verb", "to search/look for"},
	{"viedä", "viedä", "verb", "to take/carry (away)"},
	{"tuoda", "tuoda", "verb", "to bring"},
	{"kantaa", "kantaa", "verb", "to carry"},
	{"panna", "panna", "verb", "to put/place"},
	{"rakastaa", "rakastaa", "verb", "to love"},
	{"tykätä", "tykätä", "verb", "to like"},
	{"pelätä", "pelätä", "verb", "to fear"},
	{"toivoa", "toivoa", "verb", "to hope/wish"},
	{"yrittää", "yrittää", "verb", "to try"},
	{"valita", "valita", "verb", "to choose"},
	{"palata", "palata", "verb", "to return"},
	{"muuttaa", "muuttaa", "verb", "to move/change"},
	{"kasvaa", "kasvaa", "verb", "to grow"},
	{"kuolla", "kuolla", "verb", "to die"},
	{"syntyä", "syntyä", "verb", "to be born"},
	{"matkustaa", "matkustaa", "verb", "to travel"},
	{"leikkiä", "leikkiä", "verb", "to play (children)"},
	{"pelata", "pelata", "verb", "to play (games/sports)"},
	{"laulaa", "laulaa", "verb", "to sing"},
	{"uida", "uida", "verb", "to swim"},

	// ── Nouns: People & Relationships (30) ──
	{"ihminen", "ihminen", "noun", "person/human"},
	{"mies", "mies", "noun", "man"},
	{"nainen", "nainen", "noun", "woman"},
	{"poika", "poika", "noun", "boy/son"},
	{"tyttö", "tyttö", "noun", "girl"},
	{"lapsi", "lapsi", "noun", "child"},
	{"vauva", "vauva", "noun", "baby"},
	{"perhe", "perhe", "noun", "family"},
	{"äiti", "äiti", "noun", "mother"},
	{"isä", "isä", "noun", "father"},
	{"veli", "veli", "noun", "brother"},
	{"sisko", "sisko", "noun", "sister"},
	{"mummo", "mummo", "noun", "grandmother"},
	{"vaari", "vaari", "noun", "grandfather"},
	{"vaimo", "vaimo", "noun", "wife"},
	{"mies", "aviomies", "noun", "husband"},
	{"ystävä", "ystävä", "noun", "friend"},
	{"kaveri", "kaveri", "noun", "friend/buddy"},
	{"naapuri", "naapuri", "noun", "neighbor"},
	{"opettaja", "opettaja", "noun", "teacher"},
	{"opiskelija", "opiskelija", "noun", "student"},
	{"lääkäri", "lääkäri", "noun", "doctor"},
	{"sairaanhoitaja", "sairaanhoitaja", "noun", "nurse"},
	{"poliisi", "poliisi", "noun", "police officer"},
	{"myyjä", "myyjä", "noun", "salesperson"},
	{"johtaja", "johtaja", "noun", "boss/leader"},
	{"työntekijä", "työntekijä", "noun", "employee/worker"},
	{"asiakas", "asiakas", "noun", "customer"},
	{"kuljettaja", "kuljettaja", "noun", "driver"},
	{"kokki", "kokki", "noun", "cook/chef"},

	// ── Nouns: Home & Household (20) ──
	{"koti", "koti", "noun", "home"},
	{"talo", "talo", "noun", "house"},
	{"asunto", "asunto", "noun", "apartment"},
	{"huone", "huone", "noun", "room"},
	{"keittiö", "keittiö", "noun", "kitchen"},
	{"olohuone", "olohuone", "noun", "living room"},
	{"makuuhuone", "makuuhuone", "noun", "bedroom"},
	{"kylpyhuone", "kylpyhuone", "noun", "bathroom"},
	{"ovi", "ovi", "noun", "door"},
	{"ikkuna", "ikkuna", "noun", "window"},
	{"lattia", "lattia", "noun", "floor"},
	{"seinä", "seinä", "noun", "wall"},
	{"tuoli", "tuoli", "noun", "chair"},
	{"pöytä", "pöytä", "noun", "table"},
	{"sänky", "sänky", "noun", "bed"},
	{"sohva", "sohva", "noun", "sofa"},
	{"avain", "avain", "noun", "key"},
	{"lamppu", "lamppu", "noun", "lamp"},
	{"peili", "peili", "noun", "mirror"},
	{"puhelin", "puhelin", "noun", "telephone/phone"},

	// ── Nouns: Food & Drink (30) ──
	{"ruoka", "ruoka", "noun", "food"},
	{"vesi", "vesi", "noun", "water"},
	{"leipä", "leipä", "noun", "bread"},
	{"maito", "maito", "noun", "milk"},
	{"kahvi", "kahvi", "noun", "coffee"},
	{"tee", "tee", "noun", "tea"},
	{"mehu", "mehu", "noun", "juice"},
	{"olut", "olut", "noun", "beer"},
	{"viini", "viini", "noun", "wine"},
	{"liha", "liha", "noun", "meat"},
	{"kala", "kala", "noun", "fish"},
	{"kana", "kana", "noun", "chicken"},
	{"juusto", "juusto", "noun", "cheese"},
	{"voi", "voi", "noun", "butter"},
	{"muna", "muna", "noun", "egg"},
	{"riisi", "riisi", "noun", "rice"},
	{"peruna", "peruna", "noun", "potato"},
	{"hedelmä", "hedelmä", "noun", "fruit"},
	{"omena", "omena", "noun", "apple"},
	{"banaani", "banaani", "noun", "banana"},
	{"tomaatti", "tomaatti", "noun", "tomato"},
	{"sipuli", "sipuli", "noun", "onion"},
	{"porkkana", "porkkana", "noun", "carrot"},
	{"salaatti", "salaatti", "noun", "salad/lettuce"},
	{"sokeri", "sokeri", "noun", "sugar"},
	{"suola", "suola", "noun", "salt"},
	{"kakku", "kakku", "noun", "cake"},
	{"jäätelö", "jäätelö", "noun", "ice cream"},
	{"lounas", "lounas", "noun", "lunch"},
	{"illallinen", "illallinen", "noun", "dinner"},
	{"aamiainen", "aamiainen", "noun", "breakfast"},
	{"ateria", "ateria", "noun", "meal"},

	// ── Nouns: Body & Health (25) ──
	{"pää", "pää", "noun", "head"},
	{"kasvot", "kasvot", "noun", "face"},
	{"silmä", "silmä", "noun", "eye"},
	{"korva", "korva", "noun", "ear"},
	{"nenä", "nenä", "noun", "nose"},
	{"suu", "suu", "noun", "mouth"},
	{"hampaat", "hammas", "noun", "teeth/tooth"},
	{"käsi", "käsi", "noun", "hand/arm"},
	{"sormi", "sormi", "noun", "finger"},
	{"jalka", "jalka", "noun", "foot/leg"},
	{"polvi", "polvi", "noun", "knee"},
	{"selkä", "selkä", "noun", "back"},
	{"vatsa", "vatsa", "noun", "stomach"},
	{"sydän", "sydän", "noun", "heart"},
	{"veri", "veri", "noun", "blood"},
	{"iho", "iho", "noun", "skin"},
	{"tukka", "tukka", "noun", "hair (on head)"},
	{"terveys", "terveys", "noun", "health"},
	{"sairaus", "sairaus", "noun", "illness/disease"},
	{"kipu", "kipu", "noun", "pain"},
	{"lääke", "lääke", "noun", "medicine"},
	{"sairaala", "sairaala", "noun", "hospital"},
	{"apteekki", "apteekki", "noun", "pharmacy"},
	{"kuume", "kuume", "noun", "fever"},
	{"flunssa", "flunssa", "noun", "flu/cold"},

	// ── Nouns: Places & Buildings (20) ──
	{"paikka", "paikka", "noun", "place"},
	{"kaupunki", "kaupunki", "noun", "city"},
	{"kylä", "kylä", "noun", "village"},
	{"maa", "maa", "noun", "country/land"},
	{"koulu", "koulu", "noun", "school"},
	{"yliopisto", "yliopisto", "noun", "university"},
	{"kirjasto", "kirjasto", "noun", "library"},
	{"kauppa", "kauppa", "noun", "shop/store"},
	{"ravintola", "ravintola", "noun", "restaurant"},
	{"kahvila", "kahvila", "noun", "café"},
	{"pankki", "pankki", "noun", "bank"},
	{"kirkko", "kirkko", "noun", "church"},
	{"museo", "museo", "noun", "museum"},
	{"teatteri", "teatteri", "noun", "theater"},
	{"hotelli", "hotelli", "noun", "hotel"},
	{"lentokenttä", "lentokenttä", "noun", "airport"},
	{"asema", "asema", "noun", "station"},
	{"toimisto", "toimisto", "noun", "office"},
	{"tehdas", "tehdas", "noun", "factory"},
	{"puisto", "puisto", "noun", "park"},

	// ── Nouns: Nature & Weather (25) ──
	{"luonto", "luonto", "noun", "nature"},
	{"metsä", "metsä", "noun", "forest"},
	{"järvi", "järvi", "noun", "lake"},
	{"joki", "joki", "noun", "river"},
	{"meri", "meri", "noun", "sea"},
	{"ranta", "ranta", "noun", "beach/shore"},
	{"saari", "saari", "noun", "island"},
	{"vuori", "vuori", "noun", "mountain"},
	{"kenttä", "kenttä", "noun", "field"},
	{"puu", "puu", "noun", "tree/wood"},
	{"kukka", "kukka", "noun", "flower"},
	{"ruoho", "ruoho", "noun", "grass"},
	{"kivi", "kivi", "noun", "stone/rock"},
	{"sää", "sää", "noun", "weather"},
	{"aurinko", "aurinko", "noun", "sun"},
	{"kuu", "kuu", "noun", "moon/month"},
	{"tähti", "tähti", "noun", "star"},
	{"taivas", "taivas", "noun", "sky/heaven"},
	{"pilvi", "pilvi", "noun", "cloud"},
	{"sade", "sade", "noun", "rain"},
	{"lumi", "lumi", "noun", "snow"},
	{"jää", "jää", "noun", "ice"},
	{"tuuli", "tuuli", "noun", "wind"},
	{"ilma", "ilma", "noun", "air/weather"},
	{"kevät", "kevät", "noun", "spring"},
	{"kesä", "kesä", "noun", "summer"},
	{"syksy", "syksy", "noun", "autumn/fall"},
	{"talvi", "talvi", "noun", "winter"},

	// ── Nouns: Time & Calendar (15) ──
	{"aika", "aika", "noun", "time"},
	{"päivä", "päivä", "noun", "day"},
	{"yö", "yö", "noun", "night"},
	{"aamu", "aamu", "noun", "morning"},
	{"ilta", "ilta", "noun", "evening"},
	{"iltapäivä", "iltapäivä", "noun", "afternoon"},
	{"tunti", "tunti", "noun", "hour/lesson"},
	{"minuutti", "minuutti", "noun", "minute"},
	{"vuosi", "vuosi", "noun", "year"},
	{"kuukausi", "kuukausi", "noun", "month"},
	{"viikko", "viikko", "noun", "week"},
	{"viikonloppu", "viikonloppu", "noun", "weekend"},
	{"juhla", "juhla", "noun", "celebration/party"},
	{"joulu", "joulu", "noun", "Christmas"},
	{"loma", "loma", "noun", "holiday/vacation"},

	// ── Nouns: Transport & Travel (15) ──
	{"auto", "auto", "noun", "car"},
	{"bussi", "bussi", "noun", "bus"},
	{"juna", "juna", "noun", "train"},
	{"lentokone", "lentokone", "noun", "airplane"},
	{"laiva", "laiva", "noun", "ship"},
	{"polkupyörä", "polkupyörä", "noun", "bicycle"},
	{"tie", "tie", "noun", "road/way"},
	{"katu", "katu", "noun", "street"},
	{"silta", "silta", "noun", "bridge"},
	{"lippu", "lippu", "noun", "ticket/flag"},
	{"matka", "matka", "noun", "trip/journey"},
	{"kartta", "kartta", "noun", "map"},
	{"laukku", "laukku", "noun", "bag"},
	{"matkalaukku", "matkalaukku", "noun", "suitcase"},
	{"passi", "passi", "noun", "passport"},

	// ── Nouns: Clothing (12) ──
	{"vaatteet", "vaate", "noun", "clothes/clothing"},
	{"paita", "paita", "noun", "shirt"},
	{"housut", "housut", "noun", "pants/trousers"},
	{"takki", "takki", "noun", "jacket/coat"},
	{"mekko", "mekko", "noun", "dress"},
	{"hame", "hame", "noun", "skirt"},
	{"kengät", "kenkä", "noun", "shoes"},
	{"sukat", "sukka", "noun", "socks/stockings"},
	{"hattu", "hattu", "noun", "hat"},
	{"hanskat", "hansikas", "noun", "gloves"},
	{"huivi", "huivi", "noun", "scarf"},
	{"puku", "puku", "noun", "suit/costume"},

	// ── Nouns: Animals (15) ──
	{"eläin", "eläin", "noun", "animal"},
	{"koira", "koira", "noun", "dog"},
	{"kissa", "kissa", "noun", "cat"},
	{"hevonen", "hevonen", "noun", "horse"},
	{"lehmä", "lehmä", "noun", "cow"},
	{"sika", "sika", "noun", "pig"},
	{"lammas", "lammas", "noun", "sheep"},
	{"lintu", "lintu", "noun", "bird"},
	{"karhu", "karhu", "noun", "bear"},
	{"susi", "susi", "noun", "wolf"},
	{"kettu", "kettu", "noun", "fox"},
	{"jänis", "jänis", "noun", "hare/rabbit"},
	{"hirvi", "hirvi", "noun", "moose/elk"},
	{"poro", "poro", "noun", "reindeer"},
	{"hylje", "hylje", "noun", "seal"},

	// ── Nouns: Abstract & Everyday (30) ──
	{"asia", "asia", "noun", "thing/matter"},
	{"nimi", "nimi", "noun", "name"},
	{"kieli", "kieli", "noun", "language/tongue"},
	{"sana", "sana", "noun", "word"},
	{"lause", "lause", "noun", "sentence"},
	{"kirja", "kirja", "noun", "book"},
	{"lehti", "lehti", "noun", "newspaper/leaf"},
	{"kirje", "kirje", "noun", "letter (mail)"},
	{"viesti", "viesti", "noun", "message"},
	{"kysymys", "kysymys", "noun", "question"},
	{"vastaus", "vastaus", "noun", "answer"},
	{"ongelma", "ongelma", "noun", "problem"},
	{"ratkaisu", "ratkaisu", "noun", "solution"},
	{"syy", "syy", "noun", "reason/cause"},
	{"tapa", "tapa", "noun", "way/habit"},
	{"idea", "idea", "noun", "idea"},
	{"suunnitelma", "suunnitelma", "noun", "plan"},
	{"osa", "osa", "noun", "part"},
	{"numero", "numero", "noun", "number"},
	{"raha", "raha", "noun", "money"},
	{"hinta", "hinta", "noun", "price"},
	{"työ", "työ", "noun", "work/job"},
	{"elämä", "elämä", "noun", "life"},
	{"kuolema", "kuolema", "noun", "death"},
	{"rakkaus", "rakkaus", "noun", "love"},
	{"ilo", "ilo", "noun", "joy/happiness"},
	{"suru", "suru", "noun", "sorrow/grief"},
	{"pelko", "pelko", "noun", "fear"},
	{"totuus", "totuus", "noun", "truth"},
	{"uutinen", "uutinen", "noun", "news item"},

	// ── Nouns: Technology & Modern (10) ──
	{"tietokone", "tietokone", "noun", "computer"},
	{"internet", "internet", "noun", "internet"},
	{"sähköposti", "sähköposti", "noun", "email"},
	{"ohjelma", "ohjelma", "noun", "program/show"},
	{"kuva", "kuva", "noun", "picture/image"},
	{"video", "video", "noun", "video"},
	{"musiikki", "musiikki", "noun", "music"},
	{"elokuva", "elokuva", "noun", "movie/film"},
	{"peli", "peli", "noun", "game"},
	{"televisio", "televisio", "noun", "television"},

	// ── Adjectives (45) ──
	{"hyvä", "hyvä", "adjective", "good"},
	{"huono", "huono", "adjective", "bad"},
	{"suuri", "suuri", "adjective", "big/great"},
	{"pieni", "pieni", "adjective", "small/little"},
	{"uusi", "uusi", "adjective", "new"},
	{"vanha", "vanha", "adjective", "old"},
	{"nuori", "nuori", "adjective", "young"},
	{"pitkä", "pitkä", "adjective", "long/tall"},
	{"lyhyt", "lyhyt", "adjective", "short"},
	{"kaunis", "kaunis", "adjective", "beautiful"},
	{"ruma", "ruma", "adjective", "ugly"},
	{"helppo", "helppo", "adjective", "easy"},
	{"vaikea", "vaikea", "adjective", "difficult"},
	{"tärkeä", "tärkeä", "adjective", "important"},
	{"nopea", "nopea", "adjective", "fast"},
	{"hidas", "hidas", "adjective", "slow"},
	{"kallis", "kallis", "adjective", "expensive"},
	{"halpa", "halpa", "adjective", "cheap"},
	{"lämmin", "lämmin", "adjective", "warm"},
	{"kylmä", "kylmä", "adjective", "cold"},
	{"kuuma", "kuuma", "adjective", "hot"},
	{"vahva", "vahva", "adjective", "strong"},
	{"heikko", "heikko", "adjective", "weak"},
	{"rikas", "rikas", "adjective", "rich"},
	{"köyhä", "köyhä", "adjective", "poor"},
	{"sairas", "sairas", "adjective", "sick/ill"},
	{"terve", "terve", "adjective", "healthy/hello"},
	{"väsynyt", "väsynyt", "adjective", "tired"},
	{"iloinen", "iloinen", "adjective", "happy/cheerful"},
	{"surullinen", "surullinen", "adjective", "sad"},
	{"vihainen", "vihainen", "adjective", "angry"},
	{"onnellinen", "onnellinen", "adjective", "happy/fortunate"},
	{"hiljainen", "hiljainen", "adjective", "quiet/silent"},
	{"äänekäs", "äänekäs", "adjective", "loud/noisy"},
	{"puhdas", "puhdas", "adjective", "clean/pure"},
	{"likainen", "likainen", "adjective", "dirty"},
	{"märkä", "märkä", "adjective", "wet"},
	{"kuiva", "kuiva", "adjective", "dry"},
	{"oikea", "oikea", "adjective", "right/correct"},
	{"väärä", "väärä", "adjective", "wrong"},
	{"vapaa", "vapaa", "adjective", "free"},
	{"valmis", "valmis", "adjective", "ready/finished"},
	{"täysi", "täysi", "adjective", "full"},
	{"tyhjä", "tyhjä", "adjective", "empty"},
	{"avoin", "avoin", "adjective", "open"},

	// ── Colors (10) ──
	{"punainen", "punainen", "adjective", "red"},
	{"sininen", "sininen", "adjective", "blue"},
	{"vihreä", "vihreä", "adjective", "green"},
	{"keltainen", "keltainen", "adjective", "yellow"},
	{"valkoinen", "valkoinen", "adjective", "white"},
	{"musta", "musta", "adjective", "black"},
	{"harmaa", "harmaa", "adjective", "gray"},
	{"ruskea", "ruskea", "adjective", "brown"},
	{"oranssi", "oranssi", "adjective", "orange"},
	{"vaaleanpunainen", "vaaleanpunainen", "adjective", "pink"},

	// ── Numbers (15) ──
	{"yksi", "yksi", "numeral", "one"},
	{"kaksi", "kaksi", "numeral", "two"},
	{"kolme", "kolme", "numeral", "three"},
	{"neljä", "neljä", "numeral", "four"},
	{"viisi", "viisi", "numeral", "five"},
	{"kuusi", "kuusi", "numeral", "six"},
	{"seitsemän", "seitsemän", "numeral", "seven"},
	{"kahdeksan", "kahdeksan", "numeral", "eight"},
	{"yhdeksän", "yhdeksän", "numeral", "nine"},
	{"kymmenen", "kymmenen", "numeral", "ten"},
	{"sata", "sata", "numeral", "hundred"},
	{"tuhat", "tuhat", "numeral", "thousand"},
	{"miljoona", "miljoona", "numeral", "million"},
	{"ensimmäinen", "ensimmäinen", "numeral", "first"},
	{"viimeinen", "viimeinen", "numeral", "last"},

	// ── Adverbs (30) ──
	{"nyt", "nyt", "adverb", "now"},
	{"tänään", "tänään", "adverb", "today"},
	{"huomenna", "huomenna", "adverb", "tomorrow"},
	{"eilen", "eilen", "adverb", "yesterday"},
	{"täällä", "täällä", "adverb", "here"},
	{"siellä", "siellä", "adverb", "there"},
	{"tänne", "tänne", "adverb", "to here"},
	{"sinne", "sinne", "adverb", "to there"},
	{"paljon", "paljon", "adverb", "much/a lot"},
	{"vähän", "vähän", "adverb", "a little"},
	{"hyvin", "hyvin", "adverb", "well/very"},
	{"huonosti", "huonosti", "adverb", "badly/poorly"},
	{"nopeasti", "nopeasti", "adverb", "quickly"},
	{"hitaasti", "hitaasti", "adverb", "slowly"},
	{"myös", "myös", "adverb", "also"},
	{"vain", "vain", "adverb", "only"},
	{"jo", "jo", "adverb", "already"},
	{"vielä", "vielä", "adverb", "still/yet"},
	{"aina", "aina", "adverb", "always"},
	{"usein", "usein", "adverb", "often"},
	{"joskus", "joskus", "adverb", "sometimes"},
	{"harvoin", "harvoin", "adverb", "rarely"},
	{"ehkä", "ehkä", "adverb", "maybe/perhaps"},
	{"melkein", "melkein", "adverb", "almost"},
	{"erittäin", "erittäin", "adverb", "extremely/very"},
	{"tarpeeksi", "tarpeeksi", "adverb", "enough"},
	{"heti", "heti", "adverb", "immediately"},
	{"pian", "pian", "adverb", "soon"},
	{"ulkona", "ulkona", "adverb", "outside"},
	{"sisällä", "sisällä", "adverb", "inside"},

	// ── Particles & Interjections (8) ──
	{"kyllä", "kyllä", "particle", "yes"},
	{"hei", "hei", "interjection", "hi/bye"},
	{"moi", "moi", "interjection", "hi (informal)"},
	{"kiitos", "kiitos", "interjection", "thank you"},
	{"anteeksi", "anteeksi", "interjection", "sorry/excuse me"},
	{"näkemiin", "näkemiin", "interjection", "goodbye"},

	// ── Question Words (8) ──
	{"miksi", "miksi", "adverb", "why"},
	{"missä", "missä", "adverb", "where"},
	{"minne", "minne", "adverb", "where to"},
	{"mistä", "mistä", "adverb", "where from"},
	{"miten", "miten", "adverb", "how"},
	{"milloin", "milloin", "adverb", "when"},
	{"kuinka", "kuinka", "adverb", "how"},
	{"paljonko", "paljonko", "adverb", "how much"},

	// ── Postpositions & Prepositions (15) ──
	{"kanssa", "kanssa", "adposition", "with"},
	{"ilman", "ilman", "adposition", "without"},
	{"ennen", "ennen", "adposition", "before"},
	{"jälkeen", "jälkeen", "adposition", "after"},
	{"lähellä", "lähellä", "adposition", "near"},
	{"kaukana", "kaukana", "adposition", "far from"},
	{"välissä", "välissä", "adposition", "between"},
	{"ympärillä", "ympärillä", "adposition", "around"},
	{"vastapäätä", "vastapäätä", "adposition", "opposite"},
	{"kohti", "kohti", "adposition", "toward"},
	{"pitkin", "pitkin", "adposition", "along"},
	{"ohi", "ohi", "adposition", "past/by"},
	{"läpi", "läpi", "adposition", "through"},
	{"yli", "yli", "adposition", "over"},
	{"ali", "ali", "adposition", "under"},

	// ── Conjunctions (12) ──
	{"ja", "ja", "conjunction", "and"},
	{"mutta", "mutta", "conjunction", "but"},
	{"tai", "tai", "conjunction", "or"},
	{"koska", "koska", "conjunction", "because"},
	{"kun", "kun", "conjunction", "when"},
	{"jos", "jos", "conjunction", "if"},
	{"että", "että", "conjunction", "that"},
	{"vaikka", "vaikka", "conjunction", "although/even if"},
	{"sekä", "sekä", "conjunction", "as well as/both"},
	{"eli", "eli", "conjunction", "that is/or"},
	{"sillä", "sillä", "conjunction", "for/because"},
	{"kuin", "kuin", "conjunction", "than/as"},

	// ── Nouns: Education & Work (10) ──
	{"luokka", "luokka", "noun", "class/classroom"},
	{"koe", "koe", "noun", "test/exam"},
	{"läksy", "läksy", "noun", "homework"},
	{"todistus", "todistus", "noun", "certificate/report card"},
	{"arvosana", "arvosana", "noun", "grade/mark"},
	{"ammatti", "ammatti", "noun", "profession/occupation"},
	{"palkka", "palkka", "noun", "salary/wage"},
	{"kokous", "kokous", "noun", "meeting"},
	{"sopimus", "sopimus", "noun", "contract/agreement"},
	{"hakemus", "hakemus", "noun", "application"},

	// ── Nouns: Finland & Culture (10) ──
	{"Suomi", "Suomi", "noun", "Finland"},
	{"suomalainen", "suomalainen", "noun", "Finn/Finnish person"},
	{"sauna", "sauna", "noun", "sauna"},
	{"sisu", "sisu", "noun", "perseverance/grit"},
	{"Helsinki", "Helsinki", "noun", "Helsinki"},
	{"juhannos", "juhannus", "noun", "Midsummer"},
	{"runeberginpäivä", "runeberginpäivä", "noun", "Runeberg Day"},
	{"itsenäisyyspäivä", "itsenäisyyspäivä", "noun", "Independence Day"},
	{"vappu", "vappu", "noun", "May Day"},
}

// seedCards inserts seed vocabulary into the cards table (idempotent).
func (db *DB) seedCards() error {
	stmt, err := db.Prepare(`
		INSERT OR IGNORE INTO cards (finnish, lemma, word_class, translation, source)
		VALUES (?, ?, ?, ?, 'seed')
	`)
	if err != nil {
		return err
	}
	defer stmt.Close()

	for _, s := range seedData {
		if _, err := stmt.Exec(s.Finnish, s.Lemma, s.WordClass, s.Translation); err != nil {
			return err
		}
	}
	return nil
}
